/**
 * Created by Administrator on 2017/2/24 0024.
 */
angular.module('routers',['ui.router'])
    .config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
        $stateProvider.state('index',{
            url:'/index',
            templateUrl:'template/index.html',
            controller:'indexCtrl'
        }).state('index.recommend',{
            url:'/recommend/:id',
            templateUrl:'template/recommend.html',
            controller:'recommendCtrl'
        }).state('index.hot',{
            url:'/hot/:id',
            templateUrl:'template/hot.html',
            controller:'hotCtrl'
        }).state('index.entertainment',{
            url:'/entertainment/:id',
            templateUrl:'template/entertainment.html',
            controller:'entertainmentCtrl'
        }).state('detail',{
            url:'/detail/:id',
            templateUrl:'template/detail.html',
            controller:'detailCtrl'
        }).state('login',{
            url:'/login',
            templateUrl:'template/login.html',
            controller:'loginCtrl'
        }).state('register',{
            url:'/register',
            templateUrl:'template/register.html',
            controller:'registerCtrl'
        })
        $urlRouterProvider.when('','/index/recommend/6')
    }]).run(['$http','cookie','$window',function($http,cookie,$window){
    $http.post('http://10.16.155.28:81/news/php/index.php/login_api/auto_login',{
        params:{
            username:cookie.getCookie('username'),
            token:cookie.getCookie('token')
        }
    }).success(function(data){
        console.log(data)
        if(data){

        }else{
            $window.location.href = '#/login'
        }
    })
}])